### PR TITLE
refactor based on testcontainers-go module recomendations 

### PR DESCRIPTION
**Pull request by gAmUssA**
- refactoring
- Refactored code to align with testcontainers-go module recomendations

### CODE REVIEW

**Comment by mdelapenya** [comment]
Let me take a deeper look and will post here my comments! Great to see progress in the Kong module.

Once done, we can publish it to our website here: https://github.com/testcontainers/community-module-registry/ ([example](https://github.com/testcontainers/community-module-registry/pull/2))

**Comment by mdelapenya** [comment]
Quick question: why kong image does not come with `/usr/local/kong/go-plugins/bin` already created by default? If that dir is widely used, then I think it should be already there, right?

UPDATE: https://github.com/Kong/docker-kong/issues/667 😄

**Comment by gAmUssA** [comment]
@mdelapenya it looks like `/usr/local/bin` should potentially work

https://docs.konghq.com/gateway/latest/plugin-development/pluginserver/plugins-kubernetes/ 

Let me try

**Comment by mdelapenya** [comment]
> it looks like /usr/local/bin should potentially work

I'm also working locally in a PR to your branch 🤝

**Comment by gAmUssA** [comment]
@mdelapenya 9b75534 uses image (not docker build)

**Comment by mdelapenya** [comment]
I get this error:

```
2023/08/10 16:06:17 [debug] 1321#0: [lua] plugins.lua:284: load_plugin(): Loading plugin: grpc-web
2023/08/10 16:06:18 [error] 1321#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:652: error parsing declarative config file /usr/local/kong/kong.yaml:
in 'services':
  - in entry 1 of 'services':
    in 'plugins':
      - in entry 1 of 'plugins':
        in 'name': plugin 'goplug' not enabled; add it to the 'plugins' configuration property
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/init.lua:652: in function 'init'
        init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:652: error parsing declarative config file /usr/local/kong/kong.yaml:
in 'services':
  - in entry 1 of 'services':
    in 'plugins':
      - in entry 1 of 'plugins':
        in 'name': plugin 'goplug' not enabled; add it to the 'plugins' configuration property
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/init.lua:652: in function 'init'
        init_by_lua:3: in main chunk
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:98: failed to start nginx (exit code: 1)

  Run with --v (verbose) or --vv (debug) for more details
```

I've set up the env vars, and copied the files to the places 🤔

**Comment by gAmUssA** [comment]
@mdelapenya update your local branch. I pushed https://github.com/gAmUssA/testcontainers-go-kong/commit/9b755346935f86538e3100af3461d06ef1f8f8a4 with update

**Comment by mdelapenya** [comment]
Reference for wasm plugins: https://github.com/Kong/proxy-wasm-go-rate-limiting/pull/1

**Comment by gAmUssA** [comment]
closed by #18

**Pull request closed without merging**
